### ISSUE TITLE
Allow to add indexes on foreign key columns

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#129]
Currently, the following configuration doesn't work as expected:

```yaml
my_collection:
  attributes:
    - name: log_id
      type: integer
      index: unique
  belongs_to: logs
```

It throws the the error:

```
[0.0.0.0] SQLSTATE[HY000]: General error: 1 duplicate column name: log_id (SQL: alter table "appxx_my_collections" add column "log_id" integer null) (status 500)
```
