### ISSUE TITLE
Allow multiple relationships with different names to relate the same collection

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#130]
Currently, it's possible to declare relationships with the following syntaxes:

**relation-type: string**

```yaml
books:
  relationships:
    belongs_to: author
```

**relation-type: array**

```yaml
books:
  relationships:
    belongs_to: 
      - author
      - publisher
```

New syntax proposal
---

Allow the previous syntaxes to work, adding the following for complex cases.

```yaml
books:
  # omit 'relationships' key

  belongs_to: 
    author: auths # same as using 'references' above
    creator: 
      references: auths
      on: field_id
      on_delete: restrict # 'cascade' or 'restrict'
      on_update: cascade  # 'cascade' or 'restrict'

  has_many: 
  # ...
```

**Comment by lucasdupin** [comment]
What about:
```yaml
books:
  relationships:
    belongs_to: 
      - author:
          model: auth
          on: field_id
          on_delete: restrict
          on_update: cascade
```
The syntax would be really similar to the current one =]

**Comment by fefranca** [comment]
I like @lucasdupin 's proposal. Just to add to the discussion, I believe the has_many / has_one declarations should preferably avoid declaring triggers. I also included opinionated default values:

```yaml
books:
  relationships:
    belongs_to: 
      - author:
          collection: auth  # defaults to 'authors' collection
          on: field_id   # defaults to {collection}_id  (auth_id using the previous line)
          # on_delete / on_update possible values: 'restrict', 'cascade', 'none'
          on_delete: restrict # default value 'restrict' for all relationships, 
          on_update: cascade  # default value 'cascade' for all relationships
auths:
  relationships:
     has_many: 
        - bestsellers:
          collection: books
          # No delete / update options 

```

**Comment by endel** [comment]
Thanks for your thoughts, guys. I'm thinking about using some [railsy](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to) nomenclature here. 

**Example:**

```yaml
books:
  belongs_to: 
    - auths
    - author:
        collection: auth  # defaults to 'authors' collection
        foreign_key: # defaults to {related}_id (author_id)
        primary_key: # defaults to '_id'
        required: true # defaults to false, since our priority is to be as free as possible
        on_delete: restrict # 'restrict', 'cascade' or 'none' (defaults to 'none')
        on_update: cascade  # 'restrict', 'cascade' or 'none' (defaults to 'none')
```

This syntax will allow future relationship features, such as [counter cache](https://github.com/doubleleft/hook/issues/88#issuecomment-75792880).

I do understand about the security concerns on `restrict`/`cascade` for on `delete`/`update` actions, but for productivity I think it's better to leave it as free as possible for developers.
