### ISSUE TITLE
lock_attributes value is being duplicated on schema cache

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#139]
When running `hook generate:schema`, lock_attributes is being generated with wrong value:

```yaml
# hook-ext/schema.yaml
collection_name:
  lock_attributes:
    - false
    - false
```

The correct value should be:

```yaml
# hook-ext/schema.yaml
collection_name:
  lock_attributes: false
```
