### ISSUE TITLE
support has many through on schema.yaml

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#145]

**Comment by endel** [comment]
Working example:

```yaml
# 'books' collection
books:
 attributes:
   - name: name
     type: string

# 'book_authors' intermediary collection
book_authors:
  relationships:
    belongs_to:
      - books
      - authors

# 'authors' collection
authors:
  attributes:
    - name: name
      type: string

  relationships:
    has_many:
      - books:
          through: book_authors
          # collection: books  # defaults to 'books' collection
          # foreign_key: author_id # defaults to {related}_id (author_id)
          # far_key: # defaults to '{relation}_id' (book_id)
          # local_key: _id # defaults to _id
          # required: true # defaults to false, since our priority is to be as free as possible
          # on_delete: restrict # 'restrict', 'cascade' or 'none' (defaults to 'none')
          # on_update: cascade  # 'restrict', 'cascade' or 'none' (defaults to 'none')
```
