### ISSUE TITLE
Seed + upload de arquivos

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#68]
Possibilitar o upload de arquivos ao fazer o seed de uma collection, através do arquivo YAML.

Hoje durante o seed do banco de dados, cada registro equivale a [um request para a dl-api](https://github.com/doubleleft/dl-api/blob/master/commandline/src/commands/db_seed.php#L34-L37).

Exemplo:

``` yaml
#
# Seed for with_files
#
truncate: true
data:
  - name: Hello
    field_with_file: 
      upload: seeds/files/image.jpg
```
