### ISSUE TITLE
Commandline: utilizar arquivo YAML para as configurações do app

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#69]
Temos um problema hoje que é versionar as configurações do aplicativo, deixar fácil de visualizar e editar.

Ao rodar `config:set`, o arquivo `dl-ext/config.yaml` local seria modificado, sem aplicar realmente a configuração. Somente após o comando `deploy` (https://github.com/doubleleft/dl-api/issues/62) as configurações seriam aplicadas.

O comando `config:remove` seria removido, e o `config` continua funcionando da mesma forma.

Exemplo de arquivo YAML:

``` yaml
#
# Application configuration and secrets
#
mail:
  driver: gmail
  username: dl.tools.sendmail@gmail.com
  password: xxxxxxx

push:
  gcm.access_key: AIzaSyCyKqmUVbA_KijoQlE_1V6yQN-DPw...
  apns.certificate: |
    Bag Attributes
        friendlyName: Apple Development IOS Push Services: com.doubleleft.debug
        localKeyID: 93 A8 06 3E 08 4A DC C6 92 EE 33 CF 5D F6 32 3B 0D C3 00 1C
    subject=/UID=com.doubleleft.debug/CN=Apple Development IOS Push Services: com.doubleleft.debug/OU=N56BB82M7F/C=BR
    issuer=/C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
    -----BEGIN CERTIFICATE-----
    MIIFjTCCBHWgAwIBAgIIFZSiF+6gRKcwDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNV...
```
