### ISSUE TITLE
declarative permissions/restrictions per collection

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#76]
We need a declarative way to define permissions/restrictions per collection.

They should be restricted per auth roles (https://github.com/doubleleft/hook/issues/111) and/or by action (create, read, update, delete).

**security.yaml**

```yaml
# collection permissions
collections:
  auths:
    # definitions

  photos:
    # definitions
```
