### ISSUE TITLE
Feature: Counter cache

### ISSUE THREAD

**Issue by endel** [doubleleft/hook#88]
Allow belongs_to relationships to cache the number of related rows. 

Like Rails: http://apidock.com/rails/ActiveRecord/Associations/ClassMethods/belongs_to

**Comment by endel** [comment]
As we're discussing on #130, the counter cache feature may be defined like this:

```yaml
authors:
  has_many: 
    - books:
        counter_cache: true # creates a field with name "books_count"
```
